root: true
extends:
  - plugin:@mysticatea/es2018
parserOptions:
  project: tsconfig.eslint.json
settings:
  node:
    tryExtensions: [".js", ".json", ".mjs", ".node", ".ts", ".tsx", ".vue"]

rules:
  # tsc does.
  "no-redeclare": "off"
  # https://github.com/typescript-eslint/typescript-eslint/issues/743
  "@mysticatea/ts/unbound-method": "off"

overrides:
  - files: "./src/unicode/ids.ts"
    rules:
      curly: "off"
      no-misleading-character-class: "off"
  - files: "./src/unicode/property-data.ts"
    rules:
      "@mysticatea/ts/camelcase": "off"
