root: true
extends:
  - plugin:@eslint-community/mysticatea/es2018
parserOptions:
  project: tsconfig.eslint.json
settings:
  node:
    tryExtensions: [".js", ".json", ".mjs", ".node", ".ts", ".tsx", ".vue"]

rules:
  # tsc does.
  "no-redeclare": "off"
  # https://github.com/typescript-eslint/typescript-eslint/issues/743
  "@eslint-community/mysticatea/ts/unbound-method": "off"

  # Temporary disabled rules
  "@eslint-community/mysticatea/ts/naming-convention": "off"
  "@eslint-community/mysticatea/ts/prefer-readonly-parameter-types": "off"
  # Should be fixed by `@eslint-community/eslint-plugin-mysticatea`
  "no-duplicate-imports": "off"
  "@eslint-community/mysticatea/ts/no-duplicate-imports":
    ["error", { includeExports: true }]

overrides:
  - files: "./src/unicode/ids.ts"
    rules:
      curly: "off"
      no-misleading-character-class: "off"
  - files: "./src/unicode/property-data.ts"
    rules:
      "@eslint-community/mysticatea/ts/camelcase": "off"
