name: cron
on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 0

permissions:
  contents: write
  pull-requests: write

jobs:
  update-unicode-resource:
    name: update-unicode-resource
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Packages
        run: npm install
      - name: Update
        run: npm run update:unicode
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "fix: updates unicode resource with latest"
          branch: update-unicode-resource
          branch-suffix: timestamp
          title: "fix: updates unicode resource with latest"

  update-test262:
    name: update-test262
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Packages
        run: npm install
      - name: Update
        run: npm run update:test262:extract
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "test: updates test cases extracted from test262"
          branch: update-test262
          branch-suffix: timestamp
          title: "test: updates test cases extracted from test262"
